/* AUTO-GENERATED by scripts/gen-icons.mjs — DO NOT EDIT */
import * as React from 'react';

/** 공통 props 타입 (원하면 strokeWidth/size 등 추가하세요) */
export type IconProps = React.SVGProps<SVGSVGElement>;

/** 내부에서 lazy import된 컴포넌트를 Suspense로 감싸는 헬퍼 */
function withSuspense<T extends React.ComponentType<any>>(LazyComp: T) {
  const Wrapped = (props: React.ComponentProps<T>) => (
    <React.Suspense fallback={null}>
      {/* @ts-expect-error: lazy component typing */}
      <LazyComp {...props} />
    </React.Suspense>
  );
  return Wrapped;
}
const Lazy_Add = React.lazy(() => import('./add.svg?react'));
const Lazy_Admin = React.lazy(() => import('./admin.svg?react'));
const Lazy_Alarm = React.lazy(() => import('./alarm.svg?react'));
const Lazy_Calendar = React.lazy(() => import('./calendar.svg?react'));
const Lazy_Check = React.lazy(() => import('./check.svg?react'));
const Lazy_Close = React.lazy(() => import('./close.svg?react'));
const Lazy_Dashboard = React.lazy(() => import('./dashboard.svg?react'));
const Lazy_Delete = React.lazy(() => import('./delete.svg?react'));
const Lazy_DownArr = React.lazy(() => import('./down_arr.svg?react'));
const Lazy_Edit = React.lazy(() => import('./edit.svg?react'));
const Lazy_FilterOff = React.lazy(() => import('./filter_off.svg?react'));
const Lazy_FilterOn = React.lazy(() => import('./filter_on.svg?react'));
const Lazy_LeftArr = React.lazy(() => import('./left_arr.svg?react'));
const Lazy_Logout = React.lazy(() => import('./logout.svg?react'));
const Lazy_MailMin = React.lazy(() => import('./mail_min.svg?react'));
const Lazy_Manager = React.lazy(() => import('./manager.svg?react'));
const Lazy_More = React.lazy(() => import('./more.svg?react'));
const Lazy_Office = React.lazy(() => import('./office.svg?react'));
const Lazy_PhoneMin = React.lazy(() => import('./phone_min.svg?react'));
const Lazy_PlaceMin = React.lazy(() => import('./place_min.svg?react'));
const Lazy_Profile = React.lazy(() => import('./profile.svg?react'));
const Lazy_Project = React.lazy(() => import('./project.svg?react'));
const Lazy_Pto = React.lazy(() => import('./pto.svg?react'));
const Lazy_RightArr = React.lazy(() => import('./right_arr.svg?react'));
const Lazy_TooltipNoti = React.lazy(() => import('./tooltip_noti.svg?react'));
const Lazy_UpArr = React.lazy(() => import('./up_arr.svg?react'));
const Lazy_Search = React.lazy(() => import('./search_gray.svg?react'));
const Lazy_File = React.lazy(() => import('./file.svg?react'));
const Lazy_CircleX = React.lazy(() => import('./circle_x.svg?react'));
const Lazy_Download = React.lazy(() => import('./download.svg?react'));

export const Add: React.FC<IconProps> = Object.assign(withSuspense(Lazy_Add), { displayName: 'Add' });
export const Admin: React.FC<IconProps> = Object.assign(withSuspense(Lazy_Admin), { displayName: 'Admin' });
export const Alarm: React.FC<IconProps> = Object.assign(withSuspense(Lazy_Alarm), { displayName: 'Alarm' });
export const Calendar: React.FC<IconProps> = Object.assign(withSuspense(Lazy_Calendar), { displayName: 'Calendar' });
export const Check: React.FC<IconProps> = Object.assign(withSuspense(Lazy_Check), { displayName: 'Check' });
export const Close: React.FC<IconProps> = Object.assign(withSuspense(Lazy_Close), { displayName: 'Close' });
export const Dashboard: React.FC<IconProps> = Object.assign(withSuspense(Lazy_Dashboard), { displayName: 'Dashboard' });
export const Delete: React.FC<IconProps> = Object.assign(withSuspense(Lazy_Delete), { displayName: 'Delete' });
export const DownArr: React.FC<IconProps> = Object.assign(withSuspense(Lazy_DownArr), { displayName: 'DownArr' });
export const Edit: React.FC<IconProps> = Object.assign(withSuspense(Lazy_Edit), { displayName: 'Edit' });
export const FilterOff: React.FC<IconProps> = Object.assign(withSuspense(Lazy_FilterOff), { displayName: 'FilterOff' });
export const FilterOn: React.FC<IconProps> = Object.assign(withSuspense(Lazy_FilterOn), { displayName: 'FilterOn' });
export const LeftArr: React.FC<IconProps> = Object.assign(withSuspense(Lazy_LeftArr), { displayName: 'LeftArr' });
export const Logout: React.FC<IconProps> = Object.assign(withSuspense(Lazy_Logout), { displayName: 'Logout' });
export const MailMin: React.FC<IconProps> = Object.assign(withSuspense(Lazy_MailMin), { displayName: 'MailMin' });
export const Manager: React.FC<IconProps> = Object.assign(withSuspense(Lazy_Manager), { displayName: 'Manager' });
export const More: React.FC<IconProps> = Object.assign(withSuspense(Lazy_More), { displayName: 'More' });
export const Office: React.FC<IconProps> = Object.assign(withSuspense(Lazy_Office), { displayName: 'Office' });
export const PhoneMin: React.FC<IconProps> = Object.assign(withSuspense(Lazy_PhoneMin), { displayName: 'PhoneMin' });
export const PlaceMin: React.FC<IconProps> = Object.assign(withSuspense(Lazy_PlaceMin), { displayName: 'PlaceMin' });
export const Profile: React.FC<IconProps> = Object.assign(withSuspense(Lazy_Profile), { displayName: 'Profile' });
export const Project: React.FC<IconProps> = Object.assign(withSuspense(Lazy_Project), { displayName: 'Project' });
export const Pto: React.FC<IconProps> = Object.assign(withSuspense(Lazy_Pto), { displayName: 'Pto' });
export const RightArr: React.FC<IconProps> = Object.assign(withSuspense(Lazy_RightArr), { displayName: 'RightArr' });
export const TooltipNoti: React.FC<IconProps> = Object.assign(withSuspense(Lazy_TooltipNoti), { displayName: 'TooltipNoti' });
export const UpArr: React.FC<IconProps> = Object.assign(withSuspense(Lazy_UpArr), { displayName: 'UpArr' });
export const Search: React.FC<IconProps> = Object.assign(withSuspense(Lazy_Search), { displayName: 'Search' });
export const File: React.FC<IconProps> = Object.assign(withSuspense(Lazy_File), { displayName: 'File' });
export const CircleX: React.FC<IconProps> = Object.assign(withSuspense(Lazy_CircleX), { displayName: 'CircleX' });
export const Download: React.FC<IconProps> = Object.assign(withSuspense(Lazy_Download), { displayName: 'Download' });
